# Generated by Django 5.2.dev20240815065219 on 2024-08-21 20:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_cart_delete_item_delete_section'),
        ('store', '0001_initial'),
        ('usr_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCart',
            new_name='UserItem',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_creation_date', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 21, 20, 46, 26, 57612, tzinfo=datetime.timezone.utc))),
                ('expected_delivery_date', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 28, 20, 46, 26, 57681, tzinfo=datetime.timezone.utc))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
