# Generated by Django 5.2.dev20240815065219 on 2024-08-21 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_profile', '0002_rename_usercart_useritem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('message_sent_date', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 21, 22, 8, 46, 123998, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 28, 22, 8, 46, 122939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 21, 22, 8, 46, 122894, tzinfo=datetime.timezone.utc)),
        ),
    ]
