# Generated by Django 5.2.dev20240815065219 on 2024-08-21 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_profile', '0003_notification_alter_order_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_sent_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 21, 22, 58, 53, 253642, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 28, 22, 58, 53, 252360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 21, 22, 58, 53, 252312, tzinfo=datetime.timezone.utc)),
        ),
    ]
