# Generated by Django 5.2.dev20240823160747 on 2024-09-04 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_profile', '0004_alter_notification_message_sent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_sent_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 4, 22, 10, 9, 309196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 11, 22, 10, 9, 268219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 4, 22, 10, 9, 268153, tzinfo=datetime.timezone.utc)),
        ),
    ]
