# Generated by Django 5.2.dev20240903141902 on 2024-09-11 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_profile', '0005_alter_notification_message_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='New Notification', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_sent_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 11, 15, 49, 17, 580650, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 15, 49, 17, 569382, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 11, 15, 49, 17, 569364, tzinfo=datetime.timezone.utc)),
        ),
    ]
