# Generated by Django 5.2.dev20240930195228 on 2024-10-03 00:49

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_order_is_delivered_order_is_paid_for_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
    ]
