# Generated by Django 5.2.dev20240930195228 on 2025-01-01 00:53

import datetime
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='first name', max_length=40)),
                ('last_name', models.CharField(default='last name', max_length=40)),
                ('email', models.EmailField(default='useremail@mail.com', max_length=40, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('about_user', models.TextField(blank=True, max_length=300)),
                ('country_of_residence', models.CharField(blank=True, max_length=100)),
                ('state_of_residence', models.CharField(blank=True, max_length=100)),
                ('city_of_residence', models.CharField(blank=True, max_length=100)),
                ('street_address', models.TextField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos/')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
