# Generated by Django 5.2.dev20240930195228 on 2024-10-22 22:19

import django.db.models.deletion
import django.db.models.manager
import reviews.models.feedbackmodel
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=reviews.models.feedbackmodel.Feedback.get_category, max_length=40)),
                ('review', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('feedbacks', django.db.models.manager.Manager()),
            ],
        ),
    ]
