from .profile_indexview import IndexView
from .profile_orderviews import OrdersTemplateView, OrdersListView, OrderDetailView, ConfirmOrderView
from .profile_notificationviews import NotificationsListView, NotificationDetailView
from .profile_cartviews import CartView, RemoveItemView
from .upload_profile_photoview import UploadProfilePhotoView