# Generated by Django 5.2.dev20240815065219 on 2024-08-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_about_user_user_city_of_residence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
