# Generated by Django 5.2.dev20240823160747 on 2024-08-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_user_email_remove_user_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actve',
            new_name='is_active',
        ),
    ]
