# Generated by Django 5.2.dev20240903141902 on 2024-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisle',
            name='description',
            field=models.CharField(default='items', help_text='Items on this aisle', max_length=100),
        ),
    ]
