# Generated by Django 5.2.dev20240903141902 on 2024-09-23 22:25

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_aisle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='amount in store', verbose_name='Stored quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
            managers=[
                ('stocks', django.db.models.manager.Manager()),
            ],
        ),
    ]
