# Generated by Django 5.2.dev20240903141902 on 2024-09-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
