# Generated by Django 5.2.dev20240925175218 on 2024-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_stock_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='retail_unit',
            field=models.CharField(default='1 piece', help_text='retailing unit', max_length=40),
        ),
        migrations.AddField(
            model_name='item',
            name='retail_unit_price',
            field=models.PositiveIntegerField(default=0, help_text='Price of 1 retail unit in Naira', verbose_name='Retail price'),
        ),
        migrations.AddField(
            model_name='item',
            name='wholesale_unit',
            field=models.CharField(default='1 pack', help_text='unit for wholesale', max_length=40),
        ),
        migrations.AddField(
            model_name='item',
            name='wholesale_unit_price',
            field=models.PositiveIntegerField(default=0, help_text='Price of 1 wholesale unit in Naira', verbose_name='Wholesale price'),
        ),
    ]
