# Generated by Django 5.2.dev20240925175218 on 2024-09-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_item_price_item_retail_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(default='add item info here', help_text='more info on the item', verbose_name='Item Info'),
        ),
    ]
