# Generated by Django 5.2.dev20240930195228 on 2025-01-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tags',
            field=models.ManyToManyField(to='store.tag'),
        ),
    ]
